name: overlay_container
description: A flutter widget which renders its child outside the original widget hierarchy.
version: 0.0.5+1
author: Mustansir Zia <mustansir29@hotmail.com>
homepage: https://github.com/MustansirZia/overlay_container

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter